export const getAllProducts = () => {
  return [
    {
      id: 1,
      title: "Oakley Flight Deck M",
      price: 24950,
      category: "Маска",
      brand: "Oakley",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/D0OsIBf.png",
    },
    {
      id: 2,
      title: "Oakley Flight Tracker M",
      price: 20740,
      category: "Маска",
      brand: "Oakley",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/skhDcnn.png",
      img1:"https://i.imgur.com/dVQKSeo.png",
      img2:"https://i.imgur.com/XwjDrCQ.png",
      img3:"https://i.imgur.com/oxVwi5b.png",
      img4:"https://i.imgur.com/mBbmHi5.png",
    },
    {
      id: 3,
      title: "Spect Red Bull Sight",
      price: 7970,
      category: "Маска",
      brand: "Red Bull",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/HJSIdAh.png",
    },
    {
      id: 4,
      title: "Electric EG2-T.S + BL",
      price: 7970,
      category: "Маска",
      brand: "Electric",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/qP8LSnO.png",
    },
    {
      id: 5,
      title: "Sweet Protection",
      price: 11970,
      category: "Маска",
      brand: "Sweet Protection",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/gGWfvca.png",
    },
    {
      id: 6,
      title: "Deeluxe D.n.a.",
      price: 14660,
      category: "Ботинки для сноуборда",
      brand: "Deeluxe",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/RtrzOUO.png",
    },
    {
      id: 7,
      title: "Deeluxe ID Dual BOA",
      price: 40950,
      category: "Ботинки для сноуборда",
      brand: "Deeluxe",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/9wGSNrU.png",
    },
    {
      id: 8,
      title: "Burton Grom BOA",
      price: 16150,
      category: "Ботинки для сноуборда",
      brand: "Burton",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/BXQTnqs.png",
    },
    {
      id: 9,
      title: "Rome Stomp Boa",
      price: 16760,
      category: "Ботинки для сноуборда",
      brand: "Rome Stomp",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/JiGIj94.png",
    },
    {
      id: 10,
      title: "Terror Gelium",
      price: 27360,
      category: "Сноуборды",
      brand: "Terror",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/SZpVstE.png",
    },
    {
      id: 11,
      title: "Rome Mechanic",
      price: 26560,
      category: "Сноуборды",
      brand: "Rome",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/megCZYu.png",
    },
    {
      id: 12,
      title: "PRIME Simple",
      price: 17870,
      category: "Сноуборды",
      brand: "PRIME",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/JWMrem7.png",
    },
    {
      id: 13,
      title: "YES 20/20",
      price: 46460,
      category: "Сноуборды",
      brand: "YES 20/20",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/ViLrVZ6.png",
    },
    {
      id: 14,
      title: "686 W Upton Insulated",
      price: 11970,
      category: "Куртки для сноуборда",
      brand: "686",
      gender:"Мужской",
      img_url: "https://i.imgur.com/KyaJMRG.png",
    },
    {
      id: 15,
      title: "Volcom Aris INS",
      price: 18300,
      category: "Куртки для сноуборда",
      brand: "Volcom",
      gender:"Женский",
      img_url: "https://i.imgur.com/iKcasAE.png",
    },
    {
      id: 16,
      title: "Planks All-time",
      price: 19770,
      category: "Куртки для сноуборда",
      brand: "Planks",
      gender:"Унисекс",
      img_url: "https://i.imgur.com/uAfHGlt.png",
    },
    {
      id: 17,
      title: "686 M Gore-Tex Core",
      price: 43950,
      category: "Штаны для сноуборда",
      brand: "686",
      gender:"Женский",
      img_url: "https://i.imgur.com/mOsFjI8.png",
    },
    {
      id: 18,
      title: " NORRONA Lofoten Gore",
      price: 15570,
      category: "Штаны для сноуборда",
      brand: "NORRONA",
      gender:"Mужской",
      img_url: "https://i.imgur.com/vTtv3nA.png",
    },
  ];
};
